# Generated by Django 5.2.7 on 2025-11-01 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='job_type',
            field=models.CharField(default='Full-time', max_length=50),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
